<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class LichHenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('lich_hen_pets')->delete();

        DB::table('lich_hen_pets')->insert([
            [
                'id'=>1,
                'id_lich' => 1,
                'id_kh' => 1,
                'id_dv' => 1,
                'id_pet' => 1,
                'ngay' => '2025-05-08',
                'gio' => '09:00 - 10:00',
                'id_nv' => 1,
                'tinh_trang' => 0,
                'tien_coc' => 75000,
            ],
            [
                'id'=>2,
                'id_lich' => 2,
                'id_kh' => 2,
                'id_dv' => 2,
                'id_pet' => 2,
                'ngay' => '2025-05-09',
                'gio' => '10:00 - 11:00',
                'id_nv' => 2,
                'tinh_trang' => 1,
                'tien_coc' => 100000,
            ],
            [
                'id'=>3,
                'id_lich' => 3,
                'id_kh' => 3,
                'id_dv' => 1,
                'id_pet' => 3,
                'ngay' => '2025-05-10',
                'gio' => '13:00 - 14:00',
                'id_nv' => 1,
                'tinh_trang' => 0,
                'tien_coc' => 80000,
            ],
            [
                'id'=>4,
                'id_lich' => 4,
                'id_kh' => 1,
                'id_dv' => 3,
                'id_pet' => 4,
                'ngay' => '2025-05-11',
                'gio' => '15:00 - 16:00',
                'id_nv' => 3,
                'tinh_trang' => 1,
                'tien_coc' => 50000,
            ],
            [
                'id'=>5,
                'id_lich' => 5,
                'id_kh' => 2,
                'id_dv' => 4,
                'id_pet' => 5,
                'ngay' => '2025-05-12',
                'gio' => '08:00 - 09:00',
                'id_nv' => 2,
                'tinh_trang' => 0,
                'tien_coc' => 120000,
            ],
            [
                'id'=>6,
                'id_lich' => 6,
                'id_kh' => 2,
                'id_dv' => 2,
                'id_pet' => 6,
                'ngay' => '2025-05-13',
                'gio' => '14:00 - 15:00',
                'id_nv' => 1,
                'tinh_trang' => 1,
                'tien_coc' => 95000,
            ],
            [
                'id'=>7,
                'id_lich' => 7,
                'id_kh' => 4,
                'id_dv' => 5,
                'id_pet' => 7,
                'ngay' => '2025-05-14',
                'gio' => '14:00 - 15:00',
                'id_nv' => 2,
                'tinh_trang' => 0,
                'tien_coc' => 95000,
            ],
            [
                'id'=>8,
                'id_lich' => 1,
                'id_kh' => 4,
                'id_dv' => 6,
                'id_pet' => 8,
                'ngay' => '2025-05-17',
                'gio' => '14:00 - 15:00',
                'id_nv' => 3,
                'tinh_trang' => 0,
                'tien_coc' => 150000,
            ],
            [
                'id' => 9,
                'id_lich' => 2,
                'id_kh' => 5,
                'id_dv' => 7,
                'id_pet' => 9,
                'ngay' => '2025-05-18',
                'gio' => '19:00 - 20:00',
                'id_nv' => 4,
                'tinh_trang' => 0,
                'tien_coc' => 140000,
            ],
            [
                'id' => 10,
                'id_lich' => 3,
                'id_kh' => 3,
                'id_dv' => 8,
                'id_pet' => 10,
                'ngay' => '2025-05-19',
                'gio' => '20:00 - 21:00',
                'id_nv' => 5,
                'tinh_trang' => 1,
                'tien_coc' => 150000,
            ],
            [
                'id' => 11,
                'id_lich' => 4,
                'id_kh' => 1,
                'id_dv' => 9,
                'id_pet' => 11,
                'ngay' => '2025-05-20',
                'gio' => '09:00 - 10:00',
                'id_nv' => 1,
                'tinh_trang' => 0,
                'tien_coc' => 160000,
            ],
            [
                'id' => 12,
                'id_lich' => 5,
                'id_kh' => 2,
                'id_dv' => 10,
                'id_pet' => 12,
                'ngay' => '2025-05-21',
                'gio' => '10:00 - 11:00',
                'id_nv' => 2,
                'tinh_trang' => 1,
                'tien_coc' => 170000,
            ],
            [
                'id' => 13,
                'id_lich' => 6,
                'id_kh' => 3,
                'id_dv' => 11,
                'id_pet' => 13,
                'ngay' => '2025-05-22',
                'gio' => '11:00 - 12:00',
                'id_nv' => 3,
                'tinh_trang' => 0,
                'tien_coc' => 180000,
            ],
            [
                'id' => 14,
                'id_lich' => 7,
                'id_kh' => 4,
                'id_dv' => 12,
                'id_pet' => 14,
                'ngay' => '2025-05-23',
                'gio' => '12:00 - 13:00',
                'id_nv' => 4,
                'tinh_trang' => 1,
                'tien_coc' => 190000,
            ],
            [
                'id' => 15,
                'id_lich' => 1,
                'id_kh' => 5,
                'id_dv' => 13,
                'id_pet' => 15,
                'ngay' => '2025-05-24',
                'gio' => '13:00 - 14:00',
                'id_nv' => 5,
                'tinh_trang' => 0,
                'tien_coc' => 200000,
            ],
        ]);
    }
}

